### ISSUE TITLE
subprocess.call

### ISSUE THREAD

**Issue by nightfuryyy** [thelong0705/vietnamese-id-card-ocr#1]
Chào bác.
Bác cho em hỏi tại sao lại dùng hàm
        subprocess.call(["./resources/textcleaner", "-g", "-e", "normalize",
                         "-o", "11", "-t", "5", "temp.png", "temp.png"])
Em không hiểu tác dụng của nó liên quan đến xử lý đoạn text ?

**Comment by nightfuryyy** [comment]
" cv2.imwrite(filename, img)
    text = pytesseract.image_to_string(Image.open(
        filename), lang=lang, config=config)"
Tại sao bác không truyền thẳng ảnh opencv vào, mà lại cần ảnh PIL ?

**Comment by thelong0705** [comment]
Xin lỗi vì mình không để ý thấy cái issue này nên rep hơi muộn 

> subprocess.call(["./resources/textcleaner", "-g", "-e", "normalize",
"-o", "11", "-t", "5", "temp.png", "temp.png"])

Cái hàm này mình gọi 1 cái script để làm sạch ảnh trước khi cho vào tesseract để có độ chính xác cao hơn


>Tại sao bác không truyền thẳng ảnh opencv vào, mà lại cần ảnh PIL ?

Cái này do ảnh OpenCV lưu với format BGR nên cho vào tesseract đọc sẽ bị sai nên mình mới mở ảnh bằng PIL
