### ISSUE TITLE
Config models

### ISSUE THREAD

**Issue by tuyenlepn** [thelong0705/vietnamese-id-card-ocr#10]
Mình thấy 2 file config model của fast-rcnn vs ssd đều có num class là 5, trong khi số lượng bạn extract thông tin là 7, vậy là sao bạn?

**Comment by thelong0705** [comment]
model mình chỉ detect chứng minh thư + 4 góc chứng minh thư nên có 5 class. Còn thông tin thì mình dùng thuật toán xử lý ảnh đơn thuần thôi
