### ISSUE TITLE
Train model cho chứng minh thư cũ

### ISSUE THREAD

**Issue by tuanvc** [thelong0705/vietnamese-id-card-ocr#11]
Đầu tiên xin cảm ơn bạn với repo này, mình đã thử chạy với căn cước công dân, kết quả rất tốt.

Tuy nhiên theo như comment của bạn ở các issue đã mở (#5, #6) , model của bạn chỉ train trên chứng minh thư mới (căn cước công dân) nên chạy với chứng minh thư cũ sẽ báo lỗi 'Cant find id card in image'.

Bạn có thể update README hoặc hướng dẫn thêm về cách train model cho cả chứng minh thư cũ nữa được không ạ?
Cảm ơn bạn rất nhiều!

**Comment by thelong0705** [comment]
Do không có dataset có sẵn nên về train model thì mình làm theo cái tutorial này:
https://towardsdatascience.com/building-a-toy-detector-with-tensorflow-object-detection-api-63c0fdf2ac95

Cách làm của mình là detect 4 góc của chứng minh thư rồi crop nên khi tạo dataset thì cũng cần thêm khoanh vùng 4 góc trên chứng minh thư từng ảnh.

Còn từ 4 góc để lấy được chứng minh thư gốc thì mình làm theo tutorial này:

https://www.pyimagesearch.com/2014/08/25/4-point-opencv-getperspective-transform-example/

**Comment by tuanvc** [comment]
Cảm ơn Long nhiều nhé! 
Tuyệt vời ạ!!

**Comment by HoiBunCa** [comment]
sau khi có được chứng minh thư gốc, các bước tiếp theo như thế nào, bạn có thể chỉ mình với được không? 
Cảm ơn bạn.
