### ISSUE TITLE
Cant find id card in image

### ISSUE THREAD

**Issue by doanthuan** [thelong0705/vietnamese-id-card-ocr#5]
Chào bác, mình làm theo đúng hướng dẫn bác, nhưng trả về là không thể tìm thấy card trong image.

**Comment by thelong0705** [comment]
Có lẽ model của mình chỉ train trên chứng minh thư mới nên chắc nếu ảnh input của bạn là chứng minh thư cũ thì sẽ không chạy.

**Comment by doanthuan** [comment]
Đúng rồi bạn ơi, mình debug thử thì thấy như vậy. Mình đang xử lý cho cmnd cũ luôn. Cảm ơn bác nhiều nhé
