### ISSUE TITLE
Cant find id card in image

### ISSUE THREAD

**Issue by namnn2210** [thelong0705/vietnamese-id-card-ocr#6]
Bác ơi mình detect cả căn cước công dân + chứng minh thư cũ mà nó vẫn báo 'Cant find id card in image'. Phải xử lí thế nào hả bác

**Comment by thelong0705** [comment]
Có lẽ model của mình chỉ train trên chứng minh thư mới nên chắc nếu ảnh input của bạn là chứng minh thư cũ thì sẽ không chạy.
