### ISSUE TITLE
Model training

### ISSUE THREAD

**Issue by SSpring1014** [thelong0705/vietnamese-id-card-ocr#7]
hello,I am very interested in this good code！
I tried to train the model, but it can't achieve your results！How do you train the model?

**Comment by thelong0705** [comment]
I only have a dataset of around 100 images. So i tried to apply some augmentation technique and fine-tuning some pre-trained model (rcnn, ssd, ...) to detect 4 corners of the id-card. After that i applied some traditional computer vision technique to get extract the card from image
