### ISSUE TITLE
Cropper the card

### ISSUE THREAD

**Issue by laixuanthoi** [thelong0705/vietnamese-id-card-ocr#8]
Theo mình biết bạn detect 4 góc của card để crop, vậy nếu card bị flip dọc hoặc ngang thì có thể crop đúng ko. Bạn đã thử train 4 góc thành 4 object riêng chưa?

**Comment by thelong0705** [comment]
Mình mới chỉ làm cho trường hợp card để ngang thôi còn trường hợp card dọc hoặc ngược thì model mình có thể tìm được góc nhưng khi crop sẽ vẫn là cái thẻ ở dạng dọc hoặc ngược nên các phần xử lý tiếp theo sẽ sai.

Mình nghĩ góc thì để dọc hay nghiêng thì nó vẫn là góc nên cũng không có ý nghĩa gì lắm. Để xử lý thẻ để dọc hay ngược thì hiện giờ mình cũng không có ý tưởng nào.
